Multiple bug fixes
NeuralAlchemist/cuddly pull request #75
Opened 2021-05-16 16:02 UTC by NeuralAlchemist

Bug fixes
- FormFooter
  - commentForm will now send in postid as well which is used to label the input tags correctly to each post. Otherwise, no matter where the files are selected, it gets added to the latest post
  - length is checked against undefined instead of null
- #73 ; #59 ; #54
- Likes can now be added/removed to posts and comments without a reload

## User Story 68
Uploading the same video displays a blank home page (issue #59)
(Tested thoroughly with a lot of different videos (large,medium and small size)

## User Story 70
Updating a post with image, will remove the image when it is posted (after update) (issue #54)
(Testing performed on postman) 

![Screenshot 2021-05-16 at 17 56 23](https://user-images.githubusercontent.com/43238452/118403733-103da580-b670-11eb-970f-7916f66b751b.png)

Saw a possible bug with these changes , this is #74

2021-05-16 18:15 UTC, eeels22 commented on frontend/src/components/FormFooter.jsx
> +          {buttonText.includes("comment") ? "comment" : "post"}
Please could these be capitalised?

`{buttonText.includes("comment") ? "Comment" : "Post"}`

2021-05-16 18:22 UTC, eeels22 commented on frontend/src/components/comments/CommentCard.jsx
> +      console.log(formData);
Console.logs could be removed unless you think it's handy to leave in for debugging related issues.

2021-05-16 18:26 UTC, eeels22 commented on frontend/src/components/posts/PostCard.jsx
> +      console.log(formData);
Console logs could be removed unless you think it's better to keep in for now

2021-05-16 18:29 UTC, eeels22 commented on frontend/src/components/posts/PostForm.jsx
> +
Could delete this lines and optionally move `// Clear the input field` above line 29

2021-05-16 18:32 UTC, eeels22 commented on frontend/src/pages/posts/PostsPage.jsx
> +    console.log("GETTING ALL POSTS");
Console log - delete if no longer needed

2021-05-16 18:37 UTC, eeels22 requested changes
Neat fixes Yash, good idea with the timeout! Just left a request to capitalise the button text on FormFooter and flagged a few console.logs.

2021-05-17 06:56 UTC, janko101 approved these changes
It looks great...cheers for likes not reloading

2021-05-17 07:42 UTC, eeels22 approved these changes
Great work Yash!

2021-05-17 07:42 UTC, merged